services:
  product.id:
    class: Drupal\product\ParamConverter\ProdIdParamConverter
    tags:
      - { name: paramconverter }
  product.nidorpath:
    class: Drupal\product\ParamConverter\ProductNidOrPathParamConverter
    tags:
      - { name: paramconverter }
  product.taxonomy:
    class: Drupal\product\Service\ProductTaxonomy
    arguments: ['@ibm_apim.taxonomy']
  product.plan:
    class: Drupal\product\Service\ProductPlan
    arguments: ['@language_manager', '@string_translation', '@ibm_apim.utils']